language: php

php:
  - '5.6'
  - '7.0'

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - composer dump-autoload

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/codacycoverage clover clover.xml
